name: Deploy App

on:
  push:
    branches:
      - main
    paths:
      - "*.py"
      - "requirements.txt"
      - ".env.buy.example"
      - ".env.sell.example"
      - ".github/workflows/deploy-app.yml"
      - ".github/workflows/deploy-app-reusable.yml"
  workflow_dispatch:
  repository_dispatch:
    types:
      - refresh-trading-token

jobs:
  deploy:
    uses: ./.github/workflows/deploy-app-reusable.yml
    secrets: inherit
